image: tmaier/docker-compose

services:
  - docker:dind

stages:
  - test
  - build

run_tests:
  stage: test
  image: maven:3.9.5
  script:
    - mvn test

build:
  stage: build
  image: docker:20.10.16  # Utilisez une image qui inclut le client Docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache maven
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - IMAGE_TAG=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec 2>/dev/null)
    - echo $IMAGE_TAG
    - echo "IMAGE_TAG=$IMAGE_TAG" >> .env
  script:
    - mvn clean package -Pprod
    - docker-compose build
    - docker-compose push
  only:
    - main
