image: tmaier/docker-compose

services:
  - docker:dind

stages:
  - test
  - build

run_tests:
  stage: test
  image: maven:3.9.5
  script:
    - mvn test

build:
  stage: build
  image: maven:3.9.5
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - mvn clean package
    - docker-compose build
    - docker-compose push
  only:
    - main
