version: "3.8"

services:
  app-auth:
    container_name: "app-auth"
    build:
      context: ./services/authentication_service
      dockerfile: Dockerfile

    ports:
      - "8081:8081"
  app-user:
    container_name: "app-user"
    depends_on:
      - db-user
    build:
        context: ./services/users_service
        dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
  db-user:
    container_name: "db-user"
    image: mysql:latest
    # restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: