apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: magictruks/spring-user-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  key: ddl-auto
                  name: mysql-user-config
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: mysql-host
                  name: mysql-user-config
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: mysql-database
                  name: mysql-user-config
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: mysql-user-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql-user
                  name: mysql-user-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: mysql-user-secret
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user
    app.kubernetes.io/name: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002